import { Tool } from "@modelcontextprotocol/sdk/types.js";
import type { KhefClient } from "../clients/khef-client.js";
import type { DbClient } from "../clients/db-client.js";
import type { ToolResult } from "../types.js";

function fmt(data: unknown): string {
  return JSON.stringify(data, null, 2);
}

function formatCollectionSummary(col: {
  id: string;
  handle: string;
  name: string;
  description: string | null;
  updated_at: string;
}): string {
  const lines = [`${col.name} (${col.handle})`, `  id: ${col.id}`];
  if (col.description) lines.push(`  ${col.description}`);
  lines.push(`  updated: ${col.updated_at}`);
  return lines.join("\n");
}

function formatDefinitionSummary(def: {
  id: string;
  handle: string;
  name: string;
  base_url: string | null;
  updated_at: string;
}): string {
  return `${def.name} (${def.handle}) — ${def.base_url ?? "no base url"}\n  id: ${def.id}\n  updated: ${def.updated_at}`;
}

function formatRun(run: {
  id: string;
  resolved_method: string;
  resolved_url: string;
  response_status: number | null;
  response_time_ms: number | null;
  error: string | null;
  response_body?: string | null;
  executed_at: string;
}): string {
  const lines: string[] = [];
  lines.push(`${run.resolved_method} ${run.resolved_url}`);
  if (run.error) {
    lines.push(`  ERROR: ${run.error}`);
  } else {
    lines.push(`  status: ${run.response_status} (${run.response_time_ms} ms)`);
  }
  lines.push(`  run_id: ${run.id}`);
  lines.push(`  at: ${run.executed_at}`);
  if (run.response_body) {
    const preview = run.response_body.length > 500
      ? run.response_body.slice(0, 500) + `\n... [${run.response_body.length - 500} more chars]`
      : run.response_body;
    lines.push(`  body:\n${preview.split("\n").map((l) => `    ${l}`).join("\n")}`);
  }
  return lines.join("\n");
}

/**
 * JWT-signer pre-request script template.
 * The sandbox host runtime (see sandbox.ts) exposes
 * khef.jwt.sign / khef.env / khef.request / khef.uuid / khef.log.
 */
function jwtScriptTemplate(input: {
  alg: string;
  keyVar: string;
  claimsVars: Record<string, string>;
  tokenVar: string;
  expSeconds: number;
}): string {
  const claimsLines = Object.entries(input.claimsVars)
    .map(([k, v]) => `  ${k}: ${v.startsWith("\"") ? v : `env.${v}`},`)
    .join("\n");
  // Collect every env var the template reads from: each claim whose value is
  // an env key (unquoted) + the signing key var. Dedupe to avoid redundant
  // lookups. Emit a FLAT JSON array so env.getAll sees [k1, k2, k3] — the
  // previous version wrapped JSON.stringify(array) inside another JS array
  // literal, producing a nested [[...], "keyVar"] shape that made
  // env.<keyVar> undefined.
  const envKeys = Array.from(
    new Set(
      [
        ...Object.values(input.claimsVars).filter((v) => !v.startsWith("\"")),
        input.keyVar,
      ],
    ),
  );
  return `// Auto-generated by generate_kapi_jwt_script
const env = khef.env.getAll(${JSON.stringify(envKeys)});
const now = Math.floor(Date.now() / 1000);
const claims = {
${claimsLines}
  iat: now,
  exp: now + ${input.expSeconds},
  jti: khef.uuid(),
};
const token = await khef.jwt.sign(claims, env.${input.keyVar}, { alg: "${input.alg}" });
khef.env.set("${input.tokenVar}", token);
khef.request.headers.set("Authorization", \`Bearer \${token}\`);
khef.log("Signed ${input.alg} JWT, exp ${input.expSeconds}s");
`;
}

/**
 * OAuth 2.0 client_credentials pre-request script template.
 * Emits a script that:
 *   - reads client_id/client_secret (and optional audience/scope) from env
 *   - checks a cached token + expiry, refreshes if within the buffer window
 *   - POSTs application/x-www-form-urlencoded to the token endpoint
 *   - writes the fresh token + expiry timestamp back to env
 *   - sets Authorization: Bearer on the outgoing request
 */
function clientCredentialsScriptTemplate(input: {
  tokenUrlVar: string;
  tokenPath: string;
  clientIdVar: string;
  clientSecretVar: string;
  audienceVar: string | null;
  scopeVar: string | null;
  tokenVar: string;
  tokenExpiryVar: string;
  refreshBufferSeconds: number;
  formFields: Record<string, string>;
}): string {
  const envKeys = Array.from(
    new Set(
      [
        input.tokenUrlVar,
        input.clientIdVar,
        input.clientSecretVar,
        ...(input.audienceVar ? [input.audienceVar] : []),
        ...(input.scopeVar ? [input.scopeVar] : []),
        ...Object.values(input.formFields).filter((v) => !v.startsWith("\"")),
      ],
    ),
  );

  const extraFormLines = Object.entries(input.formFields)
    .map(([k, v]) => `    ${JSON.stringify(k)}: ${v.startsWith("\"") ? v : `env.${v}`},`)
    .join("\n");

  const audienceLine = input.audienceVar
    ? `    audience: env.${input.audienceVar},\n`
    : "";
  const scopeLine = input.scopeVar ? `    scope: env.${input.scopeVar},\n` : "";

  return `// Auto-generated by generate_kapi_client_credentials_script
const env = khef.env.getAll(${JSON.stringify(envKeys)});
const tokenUrl = env.${input.tokenUrlVar} + ${JSON.stringify(input.tokenPath)};

const cachedToken = khef.env.get(${JSON.stringify(input.tokenVar)});
const expiryStr = khef.env.get(${JSON.stringify(input.tokenExpiryVar)}) || "0";
const expiryMs = parseInt(expiryStr, 10) || 0;
const bufferMs = ${input.refreshBufferSeconds} * 1000;

let token = cachedToken;
if (!token || Date.now() + bufferMs > expiryMs) {
  const body = new URLSearchParams({
    grant_type: "client_credentials",
    client_id: env.${input.clientIdVar},
    client_secret: env.${input.clientSecretVar},
${audienceLine}${scopeLine}${extraFormLines ? extraFormLines + "\n" : ""}  }).toString();

  const resp = await fetch(tokenUrl, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body,
  });
  if (!resp.ok) {
    const errText = await resp.text();
    throw new Error(\`Token fetch failed: \${resp.status} \${errText}\`);
  }
  const json = await resp.json();
  token = json.access_token;
  if (!token) {
    throw new Error("Token response missing access_token: " + JSON.stringify(json));
  }
  const expiresMs = (json.expires_in ?? 3600) * 1000;
  khef.env.set(${JSON.stringify(input.tokenVar)}, token);
  khef.env.set(${JSON.stringify(input.tokenExpiryVar)}, String(Date.now() + expiresMs));
  khef.log("Fetched new access token, expires in " + Math.round(expiresMs / 1000) + "s");
} else {
  khef.log("Using cached access token");
}

khef.request.headers.set("Authorization", \`Bearer \${token}\`);
`;
}

export const tools: Tool[] = [
  {
    name: "list_kapi_collections",
    description:
      "List all kapi collections. Each collection groups definitions, environments, and scripts independently of any khef project.",
    inputSchema: {
      type: "object",
      properties: {},
    },
  },
  {
    name: "create_kapi_collection",
    description:
      "Create a new kapi collection — the top-level grouping for definitions, environments, and scripts.",
    inputSchema: {
      type: "object",
      properties: {
        handle: { type: "string", description: "Unique kebab-case handle" },
        name: { type: "string", description: "Human-readable name" },
        description: { type: "string" },
      },
      required: ["handle", "name"],
    },
  },
  {
    name: "update_kapi_collection",
    description: "Update a kapi collection by id. Only provided fields are changed.",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string" },
        handle: { type: "string" },
        name: { type: "string" },
        description: { type: "string" },
      },
      required: ["id"],
    },
  },
  {
    name: "delete_kapi_collection",
    description:
      "Delete a kapi collection and all its definitions, requests, environments, scripts, and runs (cascade).",
    inputSchema: {
      type: "object",
      properties: { id: { type: "string" } },
      required: ["id"],
    },
  },
  {
    name: "list_kapi_definitions",
    description:
      "List kapi API definitions (request groups) for a collection. Each row returns id, handle, name, base_url, and timestamps.",
    inputSchema: {
      type: "object",
      properties: {
        collection_id: {
          type: "string",
          description: "Collection handle or UUID",
        },
      },
      required: ["collection_id"],
    },
  },
  {
    name: "create_kapi_definition",
    description:
      "Create a new kapi definition — a group of HTTP requests against a given base URL. Add individual requests via add_kapi_request.",
    inputSchema: {
      type: "object",
      properties: {
        collection_id: {
          type: "string",
          description: "Collection handle or UUID",
        },
        handle: { type: "string", description: "Unique kebab-case handle for this definition" },
        name: { type: "string", description: "Human-readable name" },
        description: { type: "string" },
        base_url: {
          type: "string",
          description: "Base URL (may include {{var}} placeholders resolved from env)",
        },
        default_auth: {
          type: "object",
          description: "Default auth config applied to requests in this definition",
        },
      },
      required: ["collection_id", "handle", "name"],
    },
  },
  {
    name: "update_kapi_definition",
    description: "Update a kapi definition by id. Only provided fields are changed.",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string" },
        handle: { type: "string" },
        name: { type: "string" },
        description: { type: "string" },
        base_url: { type: "string" },
        default_auth: { type: "object" },
      },
      required: ["id"],
    },
  },
  {
    name: "delete_kapi_definition",
    description: "Delete a kapi definition and all its requests (cascade).",
    inputSchema: {
      type: "object",
      properties: { id: { type: "string" } },
      required: ["id"],
    },
  },
  {
    name: "list_kapi_requests",
    description: "List requests inside a kapi definition, ordered by order_index.",
    inputSchema: {
      type: "object",
      properties: {
        definition_id: { type: "string" },
      },
      required: ["definition_id"],
    },
  },
  {
    name: "add_kapi_request",
    description:
      "Add a request to a kapi definition. Headers and query_params are arrays of {key, value, enabled} objects.",
    inputSchema: {
      type: "object",
      properties: {
        definition_id: { type: "string" },
        name: { type: "string" },
        method: {
          type: "string",
          enum: ["GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
        },
        path: { type: "string", description: "Path appended to the definition's base_url" },
        headers: {
          type: "array",
          items: {
            type: "object",
            properties: {
              key: { type: "string" },
              value: { type: "string" },
              enabled: { type: "boolean" },
            },
            required: ["key", "value"],
          },
        },
        query_params: {
          type: "array",
          items: {
            type: "object",
            properties: {
              key: { type: "string" },
              value: { type: "string" },
              enabled: { type: "boolean" },
            },
            required: ["key", "value"],
          },
        },
        body_type: {
          type: "string",
          enum: ["none", "raw", "form-data", "x-www-form", "binary", "graphql"],
        },
        body_content: { type: "string" },
        body_language: {
          type: "string",
          enum: ["json", "xml", "text", "graphql", "html", "yaml"],
        },
      },
      required: ["definition_id", "name", "method"],
    },
  },
  {
    name: "update_kapi_request",
    description:
      "Update a kapi request by id. Pre- and test-script content lives directly on the request — set pre_script_content / test_script_content to the JS source (or empty string to clear).",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string" },
        name: { type: "string" },
        method: { type: "string" },
        path: { type: "string" },
        headers: { type: "array" },
        query_params: { type: "array" },
        body_type: { type: "string" },
        body_content: { type: "string" },
        pre_script_content: { type: "string" },
        pre_script_language: {
          type: "string",
          enum: ["javascript", "shell"],
        },
        test_script_content: { type: "string" },
        test_script_language: {
          type: "string",
          enum: ["javascript", "shell"],
        },
      },
      required: ["id"],
    },
  },
  {
    name: "delete_kapi_request",
    description: "Delete a kapi request by id.",
    inputSchema: {
      type: "object",
      properties: { id: { type: "string" } },
      required: ["id"],
    },
  },
  {
    name: "run_kapi_request",
    description:
      "Execute a saved kapi request. Returns the recorded run (status, time, redacted headers, truncated body preview). Auth headers are redacted in the stored record.",
    inputSchema: {
      type: "object",
      properties: {
        request_id: { type: "string" },
        allow_insecure_tls: {
          type: "boolean",
          description: "Accept self-signed certs (off by default)",
        },
        timeout_ms: { type: "number" },
      },
      required: ["request_id"],
    },
  },
  {
    name: "run_kapi_ad_hoc",
    description:
      "Execute an unsaved request inside a collection. Useful for quick probes without creating a definition/request first.",
    inputSchema: {
      type: "object",
      properties: {
        collection_id: {
          type: "string",
          description: "Collection handle or UUID",
        },
        method: { type: "string" },
        url: { type: "string" },
        headers: { type: "array" },
        body: { type: "string" },
        environment_id: {
          type: "string",
          description: "Optional env to use for {{var}} interpolation",
        },
      },
      required: ["collection_id", "method", "url"],
    },
  },
  {
    name: "list_kapi_runs",
    description: "List recent kapi runs for a collection.",
    inputSchema: {
      type: "object",
      properties: {
        collection_id: { type: "string" },
        request_id: { type: "string", description: "Filter to a single request's history" },
        limit: { type: "number", description: "Default 50, max 500" },
      },
      required: ["collection_id"],
    },
  },
  {
    name: "get_kapi_run",
    description: "Get a kapi run by id (full body, not truncated).",
    inputSchema: {
      type: "object",
      properties: { id: { type: "string" } },
      required: ["id"],
    },
  },
  {
    name: "list_kapi_environments",
    description: "List kapi environments in a collection.",
    inputSchema: {
      type: "object",
      properties: { collection_id: { type: "string" } },
      required: ["collection_id"],
    },
  },
  {
    name: "create_kapi_environment",
    description:
      "Create a new kapi environment. Pass is_active=true to deactivate any other env and make this one the active one.",
    inputSchema: {
      type: "object",
      properties: {
        collection_id: { type: "string" },
        handle: { type: "string" },
        name: { type: "string" },
        is_active: { type: "boolean" },
      },
      required: ["collection_id", "handle", "name"],
    },
  },
  {
    name: "activate_kapi_environment",
    description: "Make the given kapi environment the active one for its collection.",
    inputSchema: {
      type: "object",
      properties: { id: { type: "string" } },
      required: ["id"],
    },
  },
  {
    name: "set_kapi_env_var",
    description:
      "Upsert a kapi env var. Plaintext values are stored as-is; is_secret=true encrypts with KAPI_SECRET_KEY (AES-256-GCM) and the value is redacted in all reads.",
    inputSchema: {
      type: "object",
      properties: {
        environment_id: { type: "string" },
        key: { type: "string" },
        value: { type: "string" },
        is_secret: { type: "boolean" },
        description: { type: "string" },
      },
      required: ["environment_id", "key", "value"],
    },
  },
  {
    name: "list_kapi_env_vars",
    description: "List kapi env vars for an environment. Secret values are returned redacted.",
    inputSchema: {
      type: "object",
      properties: { environment_id: { type: "string" } },
      required: ["environment_id"],
    },
  },
  {
    name: "copy_kapi_script",
    description:
      "Copy a pre- or test-script from one request to another. Scripts live as plain text on the request row, so this is a simple content copy with no attach/detach step.",
    inputSchema: {
      type: "object",
      properties: {
        source_request_id: { type: "string" },
        target_request_id: { type: "string" },
        kind: {
          type: "string",
          enum: ["pre", "test"],
          description: "Which slot to copy from the source",
        },
        target_kind: {
          type: "string",
          enum: ["pre", "test"],
          description:
            "Which slot to write to on the target. Defaults to the same kind as the source.",
        },
      },
      required: ["source_request_id", "target_request_id", "kind"],
    },
  },
  {
    name: "generate_kapi_jwt_script",
    description:
      "Write a JWT-signing pre-request script directly onto a kapi request. References env vars for the private key and claims. Overwrites any existing pre-script on the target request.",
    inputSchema: {
      type: "object",
      properties: {
        request_id: {
          type: "string",
          description: "Request to write the generated script onto",
        },
        alg: {
          type: "string",
          enum: ["HS256", "HS384", "HS512", "RS256", "RS384", "RS512", "ES256", "ES384", "ES512"],
          default: "ES256",
        },
        key_var: {
          type: "string",
          description: "Env var holding the signing key (private key or HMAC secret)",
        },
        token_var: {
          type: "string",
          default: "authToken",
          description: "Env var to write the signed token into",
        },
        exp_seconds: { type: "number", default: 300 },
        claims: {
          type: "object",
          description:
            "Map of claim names to env var keys (value is an env var name) or quoted literals (wrap in double quotes).",
        },
      },
      required: ["request_id", "key_var"],
    },
  },
  {
    name: "generate_kapi_client_credentials_script",
    description:
      "Write an OAuth 2.0 client_credentials pre-request script directly onto a kapi request. Reads client_id/client_secret (and optional audience/scope) from env, POSTs x-www-form-urlencoded to the token endpoint, caches the token + expiry in env, and sets Authorization: Bearer on the outgoing request. Tokens refresh when within refresh_buffer_seconds of expiry. Overwrites any existing pre-script on the target request.",
    inputSchema: {
      type: "object",
      properties: {
        request_id: {
          type: "string",
          description: "Request to write the generated script onto",
        },
        token_url_var: {
          type: "string",
          description:
            "Env var holding the token endpoint base URL (e.g. 'core_api_url'). The token_path is appended to it.",
        },
        token_path: {
          type: "string",
          default: "/v1/oauth/tokens",
          description: "Path appended to token_url_var to form the full token endpoint",
        },
        client_id_var: {
          type: "string",
          default: "client_id",
          description: "Env var holding the OAuth client_id",
        },
        client_secret_var: {
          type: "string",
          default: "client_secret",
          description: "Env var holding the OAuth client_secret",
        },
        audience_var: {
          type: "string",
          description:
            "Env var holding the OAuth audience (optional). Omit to skip the 'audience' form field.",
        },
        scope_var: {
          type: "string",
          description:
            "Env var holding the OAuth scope (optional). Omit to skip the 'scope' form field.",
        },
        token_var: {
          type: "string",
          default: "token",
          description: "Env var to cache the access token in",
        },
        token_expiry_var: {
          type: "string",
          default: "token_expiry",
          description: "Env var to cache the token expiry (ms since epoch) in",
        },
        refresh_buffer_seconds: {
          type: "number",
          default: 60,
          description: "Refresh the token when within this many seconds of expiry",
        },
        form_fields: {
          type: "object",
          description:
            "Extra form fields to include in the token POST. Map of field name to env var key (unquoted) or quoted literal (wrap in double quotes).",
        },
      },
      required: ["request_id", "token_url_var"],
    },
  },
];

export async function handleTool(
  name: string,
  args: Record<string, unknown>,
  client: KhefClient,
  _dbClient: DbClient
): Promise<ToolResult | null> {
  switch (name) {
    case "list_kapi_collections": {
      const result = (await client.listKapiCollections()) as {
        collections: Array<{
          id: string;
          handle: string;
          name: string;
          description: string | null;
          updated_at: string;
        }>;
      };
      if (result.collections.length === 0) {
        return {
          content: [
            {
              type: "text",
              text: "No kapi collections yet. Create one with create_kapi_collection.",
            },
          ],
        };
      }
      const text = result.collections.map(formatCollectionSummary).join("\n\n");
      return { content: [{ type: "text", text }] };
    }

    case "create_kapi_collection": {
      const result = await client.createKapiCollection({
        handle: args.handle as string,
        name: args.name as string,
        description: args.description as string | undefined,
      });
      return { content: [{ type: "text", text: fmt(result) }] };
    }

    case "update_kapi_collection": {
      const { id, ...rest } = args as { id: string; [k: string]: unknown };
      const result = await client.updateKapiCollection(id, rest);
      return { content: [{ type: "text", text: fmt(result) }] };
    }

    case "delete_kapi_collection": {
      const result = await client.deleteKapiCollection(args.id as string);
      return { content: [{ type: "text", text: fmt(result) }] };
    }

    case "list_kapi_definitions": {
      const result = (await client.listKapiDefinitions(
        args.collection_id as string
      )) as {
        definitions: Array<{
          id: string;
          handle: string;
          name: string;
          base_url: string | null;
          updated_at: string;
        }>;
      };
      if (result.definitions.length === 0) {
        return { content: [{ type: "text", text: "No kapi definitions in this collection." }] };
      }
      const text = result.definitions.map(formatDefinitionSummary).join("\n\n");
      return { content: [{ type: "text", text }] };
    }

    case "create_kapi_definition": {
      const result = await client.createKapiDefinition(args.collection_id as string, {
        handle: args.handle as string,
        name: args.name as string,
        description: args.description as string | undefined,
        base_url: args.base_url as string | undefined,
        default_auth: args.default_auth as Record<string, unknown> | undefined,
      });
      return { content: [{ type: "text", text: fmt(result) }] };
    }

    case "update_kapi_definition": {
      const { id, ...rest } = args as { id: string; [k: string]: unknown };
      const result = await client.updateKapiDefinition(id, rest);
      return { content: [{ type: "text", text: fmt(result) }] };
    }

    case "delete_kapi_definition": {
      const result = await client.deleteKapiDefinition(args.id as string);
      return { content: [{ type: "text", text: fmt(result) }] };
    }

    case "list_kapi_requests": {
      const result = (await client.listKapiRequests(args.definition_id as string)) as {
        requests: Array<{ id: string; name: string; method: string; path: string }>;
      };
      if (result.requests.length === 0) {
        return { content: [{ type: "text", text: "No requests in this definition." }] };
      }
      const text = result.requests
        .map((r) => `${r.method.padEnd(6)} ${r.name}\n  path: ${r.path}\n  id: ${r.id}`)
        .join("\n\n");
      return { content: [{ type: "text", text }] };
    }

    case "add_kapi_request": {
      const { definition_id, ...rest } = args as { definition_id: string; [k: string]: unknown };
      const result = await client.addKapiRequest(definition_id, rest as never);
      return { content: [{ type: "text", text: fmt(result) }] };
    }

    case "update_kapi_request": {
      const { id, ...rest } = args as { id: string; [k: string]: unknown };
      const result = await client.updateKapiRequest(id, rest);
      return { content: [{ type: "text", text: fmt(result) }] };
    }

    case "delete_kapi_request": {
      const result = await client.deleteKapiRequest(args.id as string);
      return { content: [{ type: "text", text: fmt(result) }] };
    }

    case "run_kapi_request": {
      const result = (await client.runKapiRequest(args.request_id as string, {
        allow_insecure_tls: args.allow_insecure_tls as boolean | undefined,
        timeout_ms: args.timeout_ms as number | undefined,
      })) as { run: Parameters<typeof formatRun>[0] };
      return { content: [{ type: "text", text: formatRun(result.run) }] };
    }

    case "run_kapi_ad_hoc": {
      const { collection_id, ...rest } = args as { collection_id: string; [k: string]: unknown };
      const result = (await client.runKapiAdHoc(collection_id, rest as never)) as {
        run: Parameters<typeof formatRun>[0];
      };
      return { content: [{ type: "text", text: formatRun(result.run) }] };
    }

    case "list_kapi_runs": {
      const result = (await client.listKapiRuns(args.collection_id as string, {
        request_id: args.request_id as string | undefined,
        limit: args.limit as number | undefined,
      })) as {
        runs: Array<{
          resolved_method: string;
          resolved_url: string;
          response_status: number | null;
          response_time_ms: number | null;
          error: string | null;
          executed_at: string;
          id: string;
        }>;
      };
      if (result.runs.length === 0) {
        return { content: [{ type: "text", text: "No runs recorded." }] };
      }
      const text = result.runs
        .map((r) => {
          const status = r.error ? `ERR (${r.error})` : `${r.response_status}`;
          return `${r.executed_at}  ${r.resolved_method.padEnd(6)} ${r.resolved_url}\n  ${status}, ${r.response_time_ms} ms  (run ${r.id})`;
        })
        .join("\n\n");
      return { content: [{ type: "text", text }] };
    }

    case "get_kapi_run": {
      const result = await client.getKapiRun(args.id as string);
      return { content: [{ type: "text", text: fmt(result) }] };
    }

    case "list_kapi_environments": {
      const result = await client.listKapiEnvironments(args.collection_id as string);
      return { content: [{ type: "text", text: fmt(result) }] };
    }

    case "create_kapi_environment": {
      const { collection_id, ...rest } = args as { collection_id: string; [k: string]: unknown };
      const result = await client.createKapiEnvironment(collection_id, {
        handle: rest.handle as string,
        name: rest.name as string,
        is_active: rest.is_active as boolean | undefined,
      });
      return { content: [{ type: "text", text: fmt(result) }] };
    }

    case "activate_kapi_environment": {
      const result = await client.activateKapiEnvironment(args.id as string);
      return { content: [{ type: "text", text: fmt(result) }] };
    }

    case "set_kapi_env_var": {
      const result = await client.setKapiEnvVar(args.environment_id as string, {
        key: args.key as string,
        value: args.value as string,
        is_secret: args.is_secret as boolean | undefined,
        description: args.description as string | undefined,
      });
      return { content: [{ type: "text", text: fmt(result) }] };
    }

    case "list_kapi_env_vars": {
      const result = await client.listKapiEnvVars(args.environment_id as string);
      return { content: [{ type: "text", text: fmt(result) }] };
    }

    case "copy_kapi_script": {
      const sourceId = args.source_request_id as string;
      const targetId = args.target_request_id as string;
      const kind = args.kind as "pre" | "test";
      const targetKind = (args.target_kind as "pre" | "test" | undefined) ?? kind;

      const source = (await client.getKapiRequest(sourceId)) as {
        request: {
          pre_script_content: string;
          pre_script_language: string;
          test_script_content: string;
          test_script_language: string;
        };
      };
      const contentField =
        kind === "pre" ? "pre_script_content" : "test_script_content";
      const languageField =
        kind === "pre" ? "pre_script_language" : "test_script_language";
      const targetContentField =
        targetKind === "pre" ? "pre_script_content" : "test_script_content";
      const targetLanguageField =
        targetKind === "pre" ? "pre_script_language" : "test_script_language";

      const content = source.request[contentField] ?? "";
      const language = source.request[languageField] ?? "javascript";

      await client.updateKapiRequest(targetId, {
        [targetContentField]: content,
        [targetLanguageField]: language,
      });

      return {
        content: [
          {
            type: "text",
            text: `Copied ${kind} script from ${sourceId} to ${targetId}${
              targetKind !== kind ? ` (as ${targetKind})` : ""
            }:\n\n${content || "(empty)"}`,
          },
        ],
      };
    }

    case "generate_kapi_jwt_script": {
      const alg = (args.alg as string | undefined) ?? "ES256";
      const tokenVar = (args.token_var as string | undefined) ?? "authToken";
      const expSeconds = (args.exp_seconds as number | undefined) ?? 300;
      const claims = (args.claims as Record<string, string> | undefined) ?? {};

      const content = jwtScriptTemplate({
        alg,
        keyVar: args.key_var as string,
        claimsVars: claims,
        tokenVar,
        expSeconds,
      });

      await client.updateKapiRequest(args.request_id as string, {
        pre_script_content: content,
        pre_script_language: "javascript",
      });

      return {
        content: [
          {
            type: "text",
            text: `Wrote ${alg} JWT pre-request script to request ${args.request_id}:\n\n${content}`,
          },
        ],
      };
    }

    case "generate_kapi_client_credentials_script": {
      const tokenPath = (args.token_path as string | undefined) ?? "/v1/oauth/tokens";
      const clientIdVar = (args.client_id_var as string | undefined) ?? "client_id";
      const clientSecretVar =
        (args.client_secret_var as string | undefined) ?? "client_secret";
      const tokenVar = (args.token_var as string | undefined) ?? "token";
      const tokenExpiryVar =
        (args.token_expiry_var as string | undefined) ?? "token_expiry";
      const refreshBufferSeconds =
        (args.refresh_buffer_seconds as number | undefined) ?? 60;
      const formFields =
        (args.form_fields as Record<string, string> | undefined) ?? {};

      const content = clientCredentialsScriptTemplate({
        tokenUrlVar: args.token_url_var as string,
        tokenPath,
        clientIdVar,
        clientSecretVar,
        audienceVar: (args.audience_var as string | undefined) ?? null,
        scopeVar: (args.scope_var as string | undefined) ?? null,
        tokenVar,
        tokenExpiryVar,
        refreshBufferSeconds,
        formFields,
      });

      await client.updateKapiRequest(args.request_id as string, {
        pre_script_content: content,
        pre_script_language: "javascript",
      });

      return {
        content: [
          {
            type: "text",
            text: `Wrote client_credentials pre-request script to request ${args.request_id}:\n\n${content}`,
          },
        ],
      };
    }

    default:
      return null;
  }
}
