-- Seed memory types (root types first, then children)
-- Note: unique constraint is on (name, COALESCE(parent_id, '00000000-...'))
INSERT INTO memory_types (name, description) VALUES
  ('user-note', 'Notes created by users for personal or team reference'),
  ('assistant-note', 'Notes generated by AI assistants during interactions or tasks'),
  ('project-note', 'Notes specific to a project, providing context or details'),
  ('user-todo', 'Tasks or to-dos created by users'),
  ('assistant-todo', 'Tasks or to-dos for AI assistants to work on'),
  ('decision', 'Architectural decisions, technical choices, and their rationale'),
  ('api', 'API documentation, endpoint descriptions, and usage examples'),
  ('reference', 'External references, links, and documentation pointers'),
  ('assistant-rule', 'Behavioral guidelines, coding standards, commit rules, etc.'),
  ('diagram', 'Diagrams and visual representations'),
  ('csv', 'Tabular data stored as CSV with spreadsheet rendering'),
  ('video', 'Video content with inline player'),
  ('canvas', 'Interactive HTML/JS/CSS content rendered in a sandboxed iframe'),
  ('knowledge', 'Project operational knowledge including commands, context, and patterns')
ON CONFLICT (name, COALESCE(parent_id, '00000000-0000-0000-0000-000000000000')) DO NOTHING;

-- Seed knowledge child types (parent_id references knowledge)
INSERT INTO memory_types (name, description, parent_id)
SELECT v.name, v.description, mt.id
FROM memory_types mt
CROSS JOIN (VALUES
  ('commands', 'CLI commands, scripts, and operational procedures'),
  ('context', 'Background information, architecture, DB schema, env setup'),
  ('pattern', 'Recurring workflows, conventions, and best practices')
) AS v(name, description)
WHERE mt.name = 'knowledge'
ON CONFLICT (name, COALESCE(parent_id, '00000000-0000-0000-0000-000000000000')) DO UPDATE SET
  description = EXCLUDED.description;

-- Seed canvas child types (parent_id references canvas)
INSERT INTO memory_types (name, description, parent_id)
SELECT v.name, v.description, mt.id
FROM memory_types mt
CROSS JOIN (VALUES
  ('widget', 'Self-contained interactive components (visualizers, calculators, dashboards)'),
  ('animation', 'Animated visual content (motion graphics, illustrative animations)'),
  ('prototype', 'UI experiments, mockups, or design explorations'),
  ('quiz', 'Interactive quizzes and assessments')
) AS v(name, description)
WHERE mt.name = 'canvas'
ON CONFLICT (name, COALESCE(parent_id, '00000000-0000-0000-0000-000000000000')) DO UPDATE SET
  description = EXCLUDED.description;
