-- Rename agent-todo and agent-note to assistant-todo and assistant-note
-- This avoids confusion with Claude Code "agents" (user-defined skills/personas)

-- Update memory_types table
-- The memory_type_statuses table uses memory_type_id (UUID) foreign key,
-- so updating the name here is all that's needed.
UPDATE memory_types SET
  name = 'assistant-todo',
  description = 'Tasks or to-dos for AI assistants to work on'
WHERE name = 'agent-todo';

UPDATE memory_types SET
  name = 'assistant-note',
  description = 'Notes generated by AI assistants during interactions or tasks'
WHERE name = 'assistant-note' OR name = 'agent-note';

-- DOWN

-- Revert memory_types table
UPDATE memory_types SET
  name = 'agent-todo',
  description = 'Tasks or to-dos generated by AI agents'
WHERE name = 'assistant-todo';

UPDATE memory_types SET
  name = 'agent-note',
  description = 'Notes generated by AI agents during interactions or tasks'
WHERE name = 'assistant-note';
